#!/bin/bash


echo "Installing the following essential packages:"

pkgs="xorg-xkill debtap flameshot wavebox-bin google-chrome brave gufw hardinfo jre plasma5-applets-eventcalendar rar etcher peek krdc kio-gdrive onedrive k3b furiusisomount gcc-fortran"

echo $pkgs

yay -S $pkgs --noconfirm

# disable brave browser message
sudo sysctl kernel.unprivileged_userns_clone=1
echo kernel.unprivileged_userns_clone = 1 | sudo tee /etc/sysctl.d/00-local-userns.conf

echo "Installation finished!"
